### ISSUE TITLE
Doesn’t support `set`

### ISSUE THREAD

**Issue by niksy** [ambassify/twig-ast#4]
When trying to parse following code:

```twig
{% set variable = app.get('variable') %}
```

Following error is thrown:

```sh
Error: Failed to parse template in state TAG_CONTROL at position 16: "{% set variable *= app.get('variable') %}\n"
```

[`set`](https://twig.symfony.com/doc/2.x/tags/set.html) is an official Twig element.

**Comment by JorgenEvens** [comment]
Thanks for reporting this, support for `set` has been added in [v1.2.0](https://github.com/ambassify/twig-ast/releases/tag/v1.2.0)
