### ISSUE TITLE
Doesn’t handle single quotes

### ISSUE THREAD

**Issue by niksy** [ambassify/twig-ast#5]
When using double quotes, code passes:

```twig
{% if foo("bar") %}{% endif %}
```

But using single quotes, code fails:

```twig
{% if foo('bar') %}{% endif %}
```

**Comment by JorgenEvens** [comment]
Hi @niksy, Thanks for creating the bug report. #6 fixes this issue, we'll be pushing a new release to NPM as soon as [your other issue](https://github.com/ambassify/twig-ast/issues/4) is resolved.

**Comment by JorgenEvens** [comment]
[v1.2.0](https://github.com/ambassify/twig-ast/releases/tag/v1.2.0) adds support for single quote strings.
